config/routes.rb
Rails.application.routes.draw do

  # get 'whishlists/index'sssssqsd
  # get 'whishlists/new'
  # get 'whishlists/create'
devise_for :users
root to: 'events#index'



  resources :events do
    resources :whishlists
    resources :guests
    get "/dashboard", to: "events#dashboard", as: :dashboard
    get "/account", to: "events#account", as: :account
    get "/select_guest", to: "events#select_guest", as: :select_guest
    resources :baskets do
      get "/update_price", to: "baskets#update_price", as: :update_price
      patch "/updated_price", to: "baskets#updated_price", as: :updated_price
    end
  end


  # resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :whishlist
  belongs_to :user
  has_one :event, through: :whishlist

  validates :quantity, presence: true
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!


  def index
    @event = Event.find(params[:event_id])
    @whishlists = Whishlist.where(event_id: params[:event_id])
    @baskets = @event.baskets.where(user_id: current_user.id)
    # all_user_baskets = current_user.baskets
    # @baskets = []
    # all_user_baskets.each do |b|
    #   if b.event.id == @event.id
    #     @baskets << b
    #   end
    # end
    # only select baskets where basket.event.id == @event.id
  end

  def update_price
    @event = Event.find(params[:event_id])
    @basket = Basket.find(params[:basket_id])
    @basket.quantity = 0
    @basket.price_in_cent = 0
  end

  def updated_price
    @event = Event.find(params[:event_id])
    @basket = Basket.find(params[:basket_id])
    @basket.update(basket_params)
    @basket.save
    redirect_to event_baskets_path(@event)
  end

  def create
    @event = Event.find(params[:event_id])
    @whishlist = Whishlist.find(params[:whishlist])
    # @basket = Basket.new
    @basket = Basket.where(whishlist_id: @whishlist.id, user_id: current_user.id).first_or_initialize
    # @basket.whishlist = @whishlist
    # @basket.user = current_user

    @basket.quantity ||= 0

    if @whishlist.quantity > 0
      @basket.quantity += 1
      @whishlist.quantity = @whishlist.quantity - 1
    end

    @basket.price_in_cent = 0
    if @basket.save && @whishlist.save
      respond_to do |format|
      format.html { redirect_to event_baskets_path(@event) }
      format.js
      end
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @basket = Basket.find(params[:id])
    @whishlist = @basket.whishlist
    case params[:sens]
    when "1"
      @basket.quantity += 1
      @whishlist.quantity -= 1
    when "-1"
      @basket.quantity -= 1
      @whishlist.quantity += 1
    end

    if @basket.quantity != 0
      if @whishlist.save! && @basket.save!
        respond_to do |format|
          format.html { redirect_to event_baskets_path(@event) }
          format.js
        end
      end
    elsif @basket.quantity.zero?
      @basket.destroy
      if @whishlist.save!
        respond_to do |format|
          format.html { redirect_to event_baskets_path(@event) }
          format.js
        end
      end
    end
    # redirect_to event_baskets_path(@event)
  end

  def edit
    @basket = Basket.find(params[:id])
    @event = Event.find(params[:event_id])
  end


  # def show
  #   @basket = Basket.find(params[:id])
  #   @whishlist = @basket.whishlist
  # end

  # def destroy
  #   @event = Event.find(params[:event_id])
  #   @basket = Basket.find(params[:id])
  #   @basket.destroy
  #   redirect_to event_baskets_path(@event)
  # end

  def select_items
    @whishlists = Whishlist.all
  end

  private

  def basket_params
    params.require(:basket).permit(:price_in_cent, :quantity)
  end
end

app/views/baskets/_button-choice.html.erb
<%= link_to event_basket_path(basket.event.id, basket.id, sens: '-1' ), method: :patch, remote: true do %>
<%= image_tag basket.whishlist.item.icon, class: "icon-selection" %><span class="basket-badge"><%= basket.quantity %></span>
<br>
<%#= link_to event_basket_update_price_path(@event, basket), "data-toggle" => "modal", "data-target" => "#modal#{basket.id}" do %>
<%# end %>

<% end %>
 <div data-toggle="modal" data-target='<%="#modal#{basket.id}"%>'>
  <% if basket.price_in_cent.nil? %>
    <%= puts "Ton #{basket.whishlist.item.name} n'a pas de prix" %>
  <% else %>
    <%= basket.price_in_cent %>€
  <% end %>
  <i class="fas fa-plus-circle price-margin-top"></i>
</div>

app/views/baskets/_form.html.erb
<div class="form_for_price">
  <%= simple_form_for [@event, basket], url: event_basket_updated_price_path(@event.id, basket)  do |f| %>
      <%= f.input :price_in_cent, label: false %>
      <%= f.submit "Ajouter un prix", :class => "btn btn-info mauve create-meal org-meal" %>
    <% end %>
</div>

app/views/baskets/_modal.html.erb
<div class="modal fade" id='<%="modal#{basket.id}"%>' tabindex="-1" role="dialog" aria-labelledby='<%="modal#{basket.id}Title"%>' aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <!-- <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Combien coûte ton meal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> -->
      <div class="modal-body">
        <div class="main">
          <div class="text-center">
            <div class="main">
              <div class="text-center">
                <%= basket.whishlist.item.name.capitalize %> :
                <%= render 'form', basket: basket %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/baskets/_whishlist-update.html.erb
<%= link_to event_baskets_path(event, whishlist: whishlist.id), method: :post, remote: true, class: "#{'inactive' if whishlist.quantity.zero?}" do %>
  <%= image_tag whishlist.item.icon, class: "icon-selection" %>
  <span class="icon-badge-basket"><%= whishlist.quantity %></span>
  <br>
  <%= whishlist.item.name %>
<% end %>

<%# protéger dans le controller (if zero arrête d'en créé) - créer la classe inactive = qui contient une image à griser et une pastille à griser - peut-être en JS faire un if zero classList inactive %>

app/views/baskets/create.js.erb
function addChoice() {
  const emptyBasket = document.getElementById("empty-basket");
  if (emptyBasket) {
  emptyBasket.remove();
  }

  const choiceHTML = "<div class='quantity-css-basket text-center' id='basket-item-id-<%= @basket.id %>'><%= j render "button-choice", basket: @basket %></div>"
  const choice = document.getElementById("basket-item-id-<%= @basket.id %>")
  const basketItem = document.querySelectorAll('.card-items .quantity-css');

  if (choice == undefined) {
    const addNewChoice = document.getElementById("choice-card");
    addNewChoice.insertAdjacentHTML('beforeend', choiceHTML);
    const newModal = document.getElementById("modal-creation");
    newModal.insertAdjacentHTML('beforeend', "<%= j render 'modal', basket: @basket %>");
  } else {
    choice.outerHTML = choiceHTML
  }
  const whishlistQuantity = document.getElementById("whishlist-item-id-<%= @whishlist.id %>");
  whishlistQuantity.innerHTML = "<%= j render 'whishlist-update', event: @event, whishlist: @whishlist %>";

}

addChoice();

app/views/baskets/edit.html.erb
<h1>modifier le prix de mes éléments :</h1>

<%= @basket.price_in_cent  %> €
<%= @basket.whishlist.item.name %>
<%= render 'form', basket: @basket %>

app/views/baskets/index.html.erb
<!-- <div class="container"> -->
  <div style="width: 100%; height: 28px;"></div>

  <div class="basket-relative">
    <div class="title-absolute">
      <button class="btn-primary btn-basket">Wishlist</button>
    </div>

     <div class="basket-card-css card-items category flex-wrap">
      <% @whishlists.each do |whishlist| %>
        <div id="whishlist-item-id-<%= whishlist.id %>" class="quantity-css-basket text-center">
          <%= render 'whishlist-update', event: @event, whishlist: whishlist %>
        </div>
      <% end %>
    </div>
  </div>




  <div class="text-center" style="margin: -15px 0 -3px 0;">
    <i class="fas fa-caret-down arrow-down"></i>
  </div>

  <div class="basket-relative">
    <div class="title-absolute">
      <button class="btn-primary btn-basket">Mes courses</button>
    </div>

    <div class="basket-card-css card-items category flex-wrap" id="choice-card">
        <% if @baskets.blank? %>
            <p id="empty-basket">Il n'y a rien dans ton panier</p>
            <% end %>
       <% @baskets.each do |basket| %>
          <div class="quantity-css-basket item-basket-padding text-center basket-font-size" id="basket-item-id-<%= basket.id %>">
            <%= render 'button-choice', basket: basket %>
          </div>
      <% end %>
    </div>
  </div>


  <div class="button-center">
    <%= link_to "Valider", event_dashboard_path(@event), :class => "btn btn-info mauve org-meal"%></div>
  </div>

   <div id="modal-creation">
     <% @baskets.each do |basket| %>
        <%= render 'modal', basket: basket %>
      <% end %>
  </div>

app/views/baskets/select_items.html.erb
<!-- <h1>The whishlist for this event</h1>
<ul>
  <#% @whishlists.each do |whishlist| %>
  <li>
    <#%= whishlist.item_id.name %>
  </li>
  <#% end %>
</ul>
 -->

app/views/baskets/show.html.erb
<h1>hello <%= @basket.user.nickname %></h1>
<%= @basket.whishlist.event.title %>
<%= @whishlist.item.name %>
<%= @whishlist.item.name %>

app/views/baskets/update.js.erb
function updateChoice() {
  const choice = document.getElementById("basket-item-id-<%= @basket.id %>")

  <% if @basket.quantity.zero? %>
    choice.remove();
  <% else %>
    const choiceHTML = "<div class='quantity-css-basket text-center' id='basket-item-id-<%= @basket.id %>'><%= j render "button-choice", basket: @basket %></div>"
    choice.outerHTML = choiceHTML
  <% end %>

  const whishlistQuantity = document.getElementById("whishlist-item-id-<%= @whishlist.id %>");
  whishlistQuantity.innerHTML = "<%= j render 'whishlist-update', event: @event, whishlist: @whishlist %>";
}

updateChoice();

app/views/baskets/update_price.erb
<%= render layout: "shared/main_layout", locals: {
  main_title: "Combien coûte ton meal ",
} do %>
  <div class="main">
    <div class="text-center">
      <%= @basket.whishlist.item.name.capitalize %> :
      <%= render 'form', basket: @basket %>
    </div>
  </div>
<% end %>