config/routes.rb
Rails.application.routes.draw do

  # get 'whishlists/index'sssssqsd
  # get 'whishlists/new'
  # get 'whishlists/create'
devise_for :users
root to: 'events#index'



  resources :events do
    resources :whishlists
    resources :guests
    get "/dashboard", to: "events#dashboard", as: :dashboard
    get "/account", to: "events#account", as: :account
    get "/select_guest", to: "events#select_guest", as: :select_guest
    resources :baskets do
      get "/update_price", to: "baskets#update_price", as: :update_price
      patch "/updated_price", to: "baskets#updated_price", as: :updated_price
    end
  end


  # resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :guests, dependent: :destroy
  has_many :whishlists, dependent: :destroy

  has_many :baskets, through: :whishlists
  has_many :users,   through: :guests
  # has_many :items, through: :whishlists

  validates :title, presence: true
  # validates :description, presence: true
  validates :address, presence: true
  validates :date, presence: true
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :set_event, only: [:edit, :dashboard, :destroy, :account]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def edit
  end

  def update
  end

  def dashboard
  end

  def destroy
  end

  def account
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :address, :date)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    # 2 cas : afficher les cartes des events auxquels on est invite, ET les evenements qu'on organise
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      # redirect_to event_whishlists_path(@event.id)
      redirect_to event_select_guest_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to root_path
  end

  def dashboard
    @event = Event.find(params[:event_id])
    @whishlists = Whishlist.where(event_id: @event.id)
    # @baskets = Basket.where(user_id: current_user.id)
    @total = @event.baskets.sum(:price_in_cent).to_f.round(2)
    @baskets_per_user = @event.baskets.group_by { |basket| basket.user }
    @guests = @event.users
  end

  def select_guest
    @event = Event.find(params[:event_id])

  # BARRE SEARCH  BARRE SEARCH  BARRE SEARCH  BARRE SEARCH  BARRE SEARCH
    if params[:query].present?
      @guests = User.where("nickname ILIKE ?", "%#{params[:query]}%")
    else
      @guests = User.where.not(id: current_user.id)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to :root
  end

  def account
    @event = Event.find(params[:event_id])
    @guests = @event.users + [@event.user]
    @whishlists = @event.whishlists
    @baskets = @event.baskets

    @total = @event.baskets.sum(:price_in_cent).to_f.round(2)
    @average = @total / @guests.count

    @baskets_per_user = @event.baskets.group_by { |basket| basket.user }

    @guests.each do |user|
      if @baskets_per_user[user].nil?
        @baskets_per_user[user] = [Basket.new(whishlist: @event.whishlists.first, user: user, quantity: 0, price_in_cent: 0)]
      end
    end

    @sum_per_person = {}
    @guests.each do |user|
      @sum_per_person[user] = 0
    end

    @difference_per_person = {}

    @baskets_per_user.each do |user, baskets|
      sum = baskets.sum { |basket| basket.price_in_cent }
      @sum_per_person[user] = sum
      @difference_per_person[user] = sum - @average
    end

    @balance_per_person = @difference_per_person.dup
    @refund_per_person = {}

    @users_sorted = @guests.sort_by { |user| @sum_per_person[user] }

    @users_sorted.reject { |user| @difference_per_person[user].positive? }.each do |user|
      user_to_refund = (@users_sorted - [user]).select do |u|
        @difference_per_person[u].positive?
      end
      user_to_refund.each do |refund|
        next if @difference_per_person[user] == 0

        total_refund = @difference_per_person[refund]
        debt = @difference_per_person[user]
        if (total_refund + debt).positive?
          @difference_per_person[refund] += debt
          @difference_per_person[user] = 0
          if @refund_per_person[user].nil?
            @refund_per_person[user] = { refund => (0 - debt) }
          else
            @refund_per_person[user][refund] = (0 - debt)
          end
        else
          @difference_per_person[refund] = 0
          @difference_per_person[user] = total_refund + debt
          if @refund_per_person[user].nil?
            @refund_per_person[user] = { refund => total_refund }
          else
            @refund_per_person[user][refund] = total_refund
          end
        end
      end
    end
    # if @difference == 0
    #   puts "tu n'as rien a payer"
    # elsif @difference > 0
    #   puts "on te doit des sous"
    # elsif @difference < 0
    #   puts "tu as des dettes"
    # end
  end

    # users_sorted => [User47, User46, User49, User48]
    # sum_per_user => {
    #   User47 => 0,
    #   User46 => 0,
    #   User49 => 10,
    #   User48 => 125
    # }

    # diff_per_user => {
    #   User47 => -36,25,
    #   User46 => -36,25,
    #   User49 => -3,75,
    #   User48 => 68,25
    # }

    # balance_per_user => {
    #   User47 => -36,25,
    #   User46 => -36,25,
    #   User49 => -3,75,
    #   User48 => 68,25
    # }

    # refund_per_person = {
    #   User47 => { User48 => 36.25 },
    #   User46 => { User48 => 32.5, User49 =>3.75 }
    # }
  private

  def event_params
    params.require(:event).permit(:title, :description, :address, :date)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= simple_form_for event do |f| %>

        <%= f.input :title, placeholder: "Titre", label: false, input_html: { class: 'form-input' } %>
        <%#= f.input :description %>
        <%= f.input :address, placeholder: "16 Villa Gaudelet Paris 11", input_html: { id: 'address-input', class: 'form-input' }, label: false  %>
      <div class="form-group m-0">
        <%= f.input :date, as: :string, input_html: { class: 'datepicker form-input' }, placeholder: "Sélectionner une date", label: false %>
        <div class="text-center">
          <%= f.submit "CREER MON MEAL", class: "btn btn-info mauve create-meal" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/account.html.erb
<%= render layout: "shared/main_layout", locals: {
  main_title: "C'est l'heure des comptes !",
} do %>

  <div class="card card-account">

    <% if @total == 0 %>
      <div class="nobody-paid"> Personne n'a renseigné le prix de son meal </div>
    <% else %>

      <% @refund_per_person.each do |user, refunds| %>
        <div class="container-account">
          <div class="box-account">
            <% if user.photo.blank?%>
              <%= image_tag "default-user.png", alt: "default user photo", class: "avatar-account", id: "navbar-wagon-menu" %>
            <% else %>
              <%= cl_image_tag user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max" %>
            <% end %>
            <p><%= user.nickname %></p>
          </div>

        <div class="box-refunds">
          <% refunds.each do |refund, amount| %>
            <div class="box-argent">
              <div class="box-account amount">
                <p><%= amount.to_f.round(2) %>€</p>
                <%= image_tag "balance-arrow.png", alt: "arrow", class: 'balance-arrow' %>
              </div>

              <div class="box-account">
                <% if refund.photo.blank?%>
                  <%= image_tag "default-user.png", alt: "default user photo", class: "avatar-account", id: "navbar-wagon-menu" %>
                <% else %>
                  <%= cl_image_tag refund.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max"  %>
                <% end %>
                <p><%= refund.nickname %></p>
              </div>
            </div>
          <% end %>
        </div>

        </div>
      <% end %>

    <% end %>
    <div class="total">
      <% average = @total/(@guests.count) %>
      <strong> Total : <%= @total %> € (<%= average.to_f.round(2) %>€/ pers)</strong>
      <%= image_tag "happy-calc.png", alt: "calculator", class: 'happy-calc2' %>
    </div>
  </div>

  <div class="button-center">
  <%= link_to "Retour", event_dashboard_path(@event), :class => "btn btn-info mauve org-meal" %>
  </div>
<% end %>

app/views/events/dashboard.html.erb
  <!-- <h1 class="text-center"><%#= @event.title %></h1> -->
  <!--   <div class="text-center"> <em>crée par <strong><%#= @event.user.nickname %> </strong></em></div> -->
  <div class="btn-double">
    <%= link_to event_account_path(@event) do %>
      <div class="equilibre">
        <%= image_tag "happy-calc.png", alt: "happy-calculator", class: 'happy-calc' %>
        <p>Equilibres</p>
      </div>
    <% end %>
    <%= link_to event_baskets_path do %>
      <div class="panier">
        <%= image_tag "happy-basket.png", alt: "happy-basket", class: 'happy-basket' %>
        <p>Courses</p>
      </div>
    <% end %>
      <!-- <div class="btn btn-info mauve org-meal2" id="btn-equilibre"><%#= link_to "EQUILIBRES", event_account_path(@event)%></div>
      <div class="btn btn-info mauve org-meal2"><%#= link_to "PANIER", event_baskets_path %></div> -->
  </div>

  <div class="details-container">
    <!--     <div class="event-details"> -->
      <div class="picto"><i class="fas fa-map-marked-alt"></i><p><%= @event.address.first(30) + "..." %></p></div>
      <div class="picto"><i class="fas fa-calendar-alt"></i><p><%= I18n.l @event.date, format: :long %></p></div>
      <!-- <div class="picto"><i class="fas fa-users faded"></i><p><%#= link_to "#{@event.guests.count + 1} invités", event_guests_path(@event) %></p></div> -->
    <!--     </div> -->
  </div>
  <!-- .strftime("%A %d %B %Y à %H:%M") -->
  <!-- LISTE LES GENS QUI VIENNENT AVEC LEUR BASKET -->
    <!--     <#% if @baskets_per_user[current_user].nil? %>
      <%#= image_tag "arrow.png", alt: "arrow", class: 'arrow' %>
      <%#= image_tag "happy-empty", alt: "empty basket", class: 'happy-empty' %>
      <p class="panier-vide">Il n'y a rien dans ton panier pour le moment</p>
    <%# else %>
    <%# end %> -->

  <div class="basket-background empty-cart">
    <%= image_tag "happy_fork.png", alt: "alttext", class: "img-dash" %>

    <% if !@baskets_per_user.key?(@event.user) %>
      <div class="container-dashboard">
        <div class="box-dashboard">
          <% if @event.user.photo.blank? %>
            <%= image_tag "default-user.png", alt: "default picture", class: "avatar2", id: "navbar-wagon-menu" %>
          <% else %>
            <%= cl_image_tag @event.user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max" %>
          <% end %>
          <%= @event.user.nickname %>
        </div>
        <div class="box-dashboard-items">
          <p>Pas de bras pas de chocolat!</p>
        </div>
      </div> <hr>
    <% end %>

    <% @baskets_per_user.each do |user, baskets| %>
      <div class="container-dashboard">

        <div class="box-dashboard">
          <% if user.photo.blank?%>
            <%= image_tag "default-user.png", alt: "default picture", class: "avatar2", id: "navbar-wagon-menu" %>
          <% else %>
            <%= cl_image_tag user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max" %>
          <% end %>
          <%= user.nickname %>
        </div>
        <% baskets.each do |basket| %>
          <div class="box-dashboard-items">
            <div class="indiv-item">
              <%= image_tag basket.whishlist.item.icon %>
              <p><%= basket.whishlist.item.name %></p>
            </div>
          </div>
        <% end %>

      </div><hr>
    <% end %>

    <% @guests.each do |guest| %>
      <% next if @baskets_per_user.key?(guest) %>
      <div class="container-dashboard">

        <div class="box-dashboard">
          <% if guest.photo.blank?%>
            <%= image_tag "default-user.png", alt: "default picture", class: "avatar2", id: "navbar-wagon-menu" %>
          <% else %>
            <%= cl_image_tag guest.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max" %>
          <% end %>
          <%= guest.nickname %>
        </div>
        <div class="box-dashboard-items">
          <p>Pas de bras pas de chocolat!</p>
        </div>

      </div><hr>
    <% end %>

  <!-- code retiré ici meme  -->

  </div>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <h2>Modifie ton Happy 1000</h2>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= simple_form_for @event do |f| %>
          <%= f.input :title, label: "Titre" %>
          <%= f.input :description %>
          <%= f.input :address, label: "Adresse", input_html: { id: 'address-input' }  %>
          <%= f.input :date, as: :string, input_html: { class: 'datepicker' } %>
          <%= f.submit "Modifier", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
</div>

app/views/events/index.html.erb
<% if current_user.guests.empty? && current_user.events.empty?  %>
  <h4 class="text-center mauve">Vous n'avez aucun meal pour le moment</h4>
<% end %>


<!-- BOUTONS POUR NAVIGER AVEC SLIDER -->
<div class="navbar-icons">
  <div class="nav1 icons selected"><%= image_tag "happy_chef.png", alt: "alttext", class: "happy-chef" %>Mes meals</div>
  <div class="nav2 icons"><%= image_tag "happy_fork.png", alt: "alttext", class: "happy-fork" %>Je participe</div>
<!--   <div class="nav3 icons"><%#= image_tag "happy_waiting.png", alt: "alttext", class: "happy-waiting" %>En attente</div> -->
  <div class="small-square carre1"></div>
  <div class="blanc"></div>
  <%= link_to "organiser un meal", new_event_path, :class => "btn btn-info mauve org-meal org-meal-wrapper" %>

</div>

<!-- <div class="buttons-index">
  <div class="btn btn-primary btn-nav nav1">En attente</div>
  <div class="btn btn-primary btn-nav nav2">Je participe</div>
  <div class="btn btn-primary btn-nav nav3">Mes meals</div>
</div> -->


  <div class="slider-container">
      <%= image_tag "cheese.png", alt: "cheese", id: "cheese-logo"  %>
      <%= image_tag "frying-pan.png", alt: "frying-pan", id: "frying-logo"  %>
      <%= image_tag "broccoli.png", alt: "broccoli", id: "broccoli-logo"  %>
      <%= image_tag "wine.png", alt: "wine", id: "wine-logo"  %>
      <%#= image_tag "carrot.png", alt: "carrot", id: "carrot-logo"  %>
    <div class="slider step1">

      <!-- IF USER IS HOSTING EVENTS -->
      <div class="slide">
        <% if !current_user.events.blank? %>
          <div class="participe">
            <!--           <div class="background"> -->
            <!--             <div class="participation">
              <%#= image_tag "happy_chef.png", alt: "alttext", class: 'happy-chef' %>
              <h3 class="section">Mes meals</h3>
            </div> -->

            <% current_user.events.each do |event| %>
              <div class="container-exterieur">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12 in-front">

                        <div class="card-trip">
                          <%= link_to event_dashboard_path(event), class: 'dashboard-path' do %>
                            <div class="card-photo">
                              <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg"> -->
                              <div class="card-background">
                                <h2 class="yellow-title"><%= event.title.capitalize %></h2>
                                <div class="card-details">
                                  <h6 class="yellow-details"><i class="far fa-calendar-alt"></i> <%= event.date.strftime("%d/%m/%Y") %></h6>
                                  <h6 class="yellow-details"><i class="far fa-clock"></i> <%= event.date.strftime("%HH%M") %></h6>
                                  <h6 class="yellow-details"><i class="fas fa-users"></i> <%= event.guests.count + 1 %></h6>
                                </div>
                              </div>
                            </div>
                          <% end %>
                          <div class="card-trip-infos">
                            <p>Organisé par <strong><%= event.user.nickname %></strong></p>
                           <!--  <p><em>"<%#= event.description %>"</em></p> -->

                            <!-- <%#= link_to edit_event_path(event) do %> -->
                              <!-- <i class="fas fa-pencil-alt"></i> -->
                            <!-- <#% end %> -->

                            <%= link_to event_path(event), method: :delete, data: { confirm: "Veux-tu vraiment supprimer ce meal ?" } do %>
                              <i class="fas fa-trash-alt"></i>
                            <% end %>

                            <% if event.user.photo.blank? %>
                                <%= image_tag "default-user.png", alt: "alttext", class: "card-trip-user2", id: "navbar-wagon-menu" %>
                            <% else %>
                                <%= cl_image_tag event.user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max", class: "card-trip-user" %>
                            <% end %>
                            <%#= cl_image_tag event.user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max", class: 'card-trip-user' %>
                            <!-- <img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="card-trip-user avatar-bordered"/> -->
                          </div>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>

          </div>
        <% end %>

      </div>

      <!-- IF USER IS INVITED TO EVENTS -->
      <div class="slide">
        <% if !current_user.guests.blank? %>
          <div class="participe">
              <!--             <div class="background"> -->
              <!-- <div class="participation">
               <%#= image_tag "happy_fork.png", alt: "attending logo", class: 'happy-fork' %>
               <h3 class="section">Je participe</h3>
              </div> -->

              <% current_user.guests.each do |guest| %>
                <div class="container-exterieur">
                  <div class="container">
                    <div class="row">
                      <div class="col-md-12 in-front">

                          <div class="card-trip">
                            <%= link_to event_dashboard_path(guest.event), class: 'dashboard-path' do %>
                              <div class="card-photo">
                                <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg"> -->
                                <div class="card-background">
                                  <h2 class="yellow-title"><%= guest.event.title %></h2>
                                  <div class="card-details">
                                    <h6 class="yellow-details"><i class="far fa-calendar-alt"></i> <%= guest.event.date.strftime("%d/%m/%Y") %></h6>
                                    <h6 class="yellow-details"><i class="far fa-clock"></i> <%= guest.event.date.strftime("%HH%M") %></h6>
                                    <h6 class="yellow-details"><i class="fas fa-users"></i> <%= guest.event.guests.count + 1 %></h6>
                                  </div>
                                </div>
                              </div>
                            <% end %>
                            <div class="card-trip-infos">
                              <p>Organisé par <strong><%= guest.event.user.nickname %></strong></p>

                              <!-- <%#= link_to edit_event_path(guest.event) do %>
                                <i class="fas fa-pencil-alt"></i>
                              <%# end %>
                              <%#= link_to event_path(guest.event), method: :delete, data: { confirm: "Veux-tu vraiment supprimer ce meal ?" } do %>
                                <i class="fas fa-trash-alt"></i>
                              <%# end %> -->

                              <% if guest.event.user.photo.blank? %>
                                  <%= image_tag "default-user.png", alt: "alttext", class: "card-trip-user2", id: "navbar-wagon-menu" %>
                              <% else %>
                                  <%= cl_image_tag guest.event.user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max", class: "card-trip-user" %>
                              <% end %>
                              <%#= cl_image_tag event.user.photo, height: 50, width: 50, crop: :fill, gravity: :face, :radius => "max", class: 'card-trip-user' %>
                            </div>
                          </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
              <%#= image_tag "cheese.png", alt: "cheese", id: "cheese-logo"  %>
              <%#= image_tag "carrot.png", alt: "carrot", id: "carrot-logo"  %>
            <!--             </div> -->

          </div>
        <% else %>
          <h5 class="text-center" style="margin-top: 20px;">Vous n'avez pas de meals pour le moment</h5>
        <% end %>
      </div>


        <!--       <div class="slide">

        <h4 class="text-center" style="margin-top: 20px;">Vous n'avez aucun meal en attente</h4>
        <div class="participe">
          <div class="background">
              <div class="participation">
               <%#= image_tag "happy_waiting.png", alt: "waiting logo", class: 'happy-waiting' %>
               <h3 class="section">En attente</h3>
              </div>
              <%#= image_tag "wine.png", alt: "wine", id: "wine-logo"  %>
          </div>
        </div>
      </div> -->
    </div>
  </div>

app/views/events/new.html.erb
<%= render layout: "shared/main_layout", locals: {
  main_title: "Crée ton prochain meal",
} do %>
  <%= render 'form', event: @event %>
<% end %>

app/views/events/select_guest.html.erb
<%= render layout: "shared/main_layout", locals: {
  main_title: "Qui sera de la party ?",
} do %>
  <div class="">
  <!-- DRAFT DYNAMIC CHECKBOXES SANS LE SEARCH - DRAFT DYNAMIC CHECKBOXES SANS LE SEARCH  -->
    <%= simple_form_for :guest_ids, method: :post, url: event_guests_path(@event) do |f|%>
      <div class="form-group">

        <div class="guest-choices">
          <% @guests.each do |guest|%>
          <div class="guest-item-id">

            <input type="checkbox" id='<%= "inlineCheckbox#{guest.id}" %>' value='<%= "#{guest.id}" %>' name="guests_ids[]">

            <label class="" for='<%= "inlineCheckbox#{guest.id}" %>'>
              <div class="guest-choice">
                <% if guest.photo.blank? %>
                  <%= image_tag "default-user.png",height: 50, width: 50, crop: :fill, alt: "alttext", class: "avatar-bordered" %>
                <% else %>
                  <%= cl_image_tag guest.photo, height: 50, width: 50, crop: :fill, class: "avatar-bordered" %>
                <% end %>
              </div>

              <div class="text-center">
                <%= guest.nickname %>
              </div>
            </label>
            </div>
          <% end %>
        </div>
        <% @shared_url = request.url %>
        <div class="button-center">
          <%= f.submit "ENVOYER L'INVIT' !", class: "btn btn-info mauve org-meal" %>
        </div>

      </div>
    <% end %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1> Description de <%= @event.title %> :</h1>
<%= @event.description %>

<%= link_to "Retour", event_dashboard_path(@event), :class => "btn-medium" %>