config/routes.rb
Rails.application.routes.draw do

  # get 'whishlists/index'sssssqsd
  # get 'whishlists/new'
  # get 'whishlists/create'
devise_for :users
root to: 'events#index'



  resources :events do
    resources :whishlists
    resources :guests
    get "/dashboard", to: "events#dashboard", as: :dashboard
    get "/account", to: "events#account", as: :account
    get "/select_guest", to: "events#select_guest", as: :select_guest
    resources :baskets do
      get "/update_price", to: "baskets#update_price", as: :update_price
      patch "/updated_price", to: "baskets#updated_price", as: :updated_price
    end
  end


  # resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/whishlist.rb
class Whishlist < ApplicationRecord
  belongs_to :item
  belongs_to :event
  has_many :baskets, dependent: :destroy
  validates :quantity, presence: true
end

app/controllers/whishlists_controller.rb
class WhishlistsController < ApplicationController
  def index
    @items = Item.all
    @event = Event.find(params[:event_id])
    @whishlists = Whishlist.where(event_id: params[:event_id])

    @whishlists_per_item = {}
    @whishlists.each do |whishlist|
      @whishlists_per_item[whishlist.item] = whishlist
    end
  end

  def new
  end

  def create
    @event = Event.find(params[:event_id])
    @item = Item.find(params[:item])
    @whishlist = Whishlist.where(event_id: @event.id, item_id: @item.id).first_or_initialize

    # @whishlist.event = @event
    # @whishlist.item = @item
    @whishlist.quantity ||= 0
    @whishlist.quantity += 1

    @user = current_user

    # @whishlist.user_id = current_user.id
    if @whishlist.save
      respond_to do |format|
        format.html { redirect_to event_whishlists_path(@event) }
        format.js
      end
    end
  end

  # def update
  #   @event = Event.find(params[:event_id])
  #   @item = Item.find(params[:item])
  #   @whishlist = Whishlist.find(params[:id])
  #   @whishlist.quantity = 1
  #   if params[:sens] == "1"
  #     @whishlist.quantity += 1
  #   end
  #   if @whishlist.save
  #     respond_to do |format|
  #       format.html { redirect_to event_whishlists_path(@event) }
  #       format.js
  #     end
  #   end
  # end

  # def destroy
  #   # @event = Event.find(params[:event_id])
  #   @whishlist = Whishlist.find(params[:id])
  #   @whishlist.destroy
  #   # redirect_to event_whishlists_path(@event)
  # end

  private

  def whislist_params
    params.require(:whishlist).permit(:quantity, :item_id, :event_id)
  end
end

app/views/whishlists/_button-basket.html.erb
  <%= link_to event_whishlist_path(whishlist.event.id, whishlist.id, sens: '-1' ), method: :patch, remote: true,  class: "quantity-css" do %>
    <i class="fas fa-minus"></i>
  <% end %>

  <%= image_tag whishlist.item.icon %>

  <%= link_to event_whishlist_path(whishlist.event_id, whishlist.id, sens: '1'), class: "quantity-css", method: :patch, remote: true do %>
      <i class="fas fa-plus"></i>
  <% end %>

  : <%= whishlist.quantity %>

  <%#=link_to event_whishlist_path(whishlist.event_id, whishlist.id), method: :delete, remote: true, data: { confirm: "Do you realy want to delete this item ?" } do %>
    <!-- <i class="fas fa-trash-alt"></i> -->
  <%# end %>

app/views/whishlists/_select-item.html.erb
<% if item.category == category %>
  <%= link_to event_whishlists_path(event, item: item.id, sens: "1"), class: "quantity-css text-center", method: :post, remote: true do %>
    <div class="food-item">
      <%= image_tag item.icon, class: "icon-selection" %>
      <p><%= item.name %></p>
      <span class="icon-badge-whishlist <%= "d-none" unless whishlists_per_item[item] %>" id="item-badge-<%= item.id %>"><%= whishlists_per_item[item].quantity if whishlists_per_item[item] %></span>
    </div>

  <% end %>
<% end %>

app/views/whishlists/create.html.erb
<h1>Whishlists#create</h1>
<p>Find me in app/views/whishlists/create.html.erb</p>

app/views/whishlists/create.js.erb
// document.querySelector("[item='<%= @item.id %>']")
//   .remove();

function updateItem() {
  const itemBadge = document.getElementById("item-badge-<%= @item.id %>");
  itemBadge.classList.remove("d-none");
  itemBadge.innerHTML = "<%= @whishlist.quantity %>";
}

updateItem();

app/views/whishlists/destroy.js.erb
document.getElementById("whishlist-item-id-<%= @whishlist.id %>")
  .remove();

app/views/whishlists/index.html.erb
<%= render layout: "shared/main_layout", locals: {
  main_title: "Qu'est-ce qu'on mange ?",
} do %><!-- <div class="container whishlist-container"> -->

  <!-- <div class="row card-container">
    <div class="col-xs-6 col-sm-6 col-md-6"> -->


      <div class="navbar-icons">
        <div class="nav11 icons selected"><%= image_tag "chicken.png", alt: "Salé", id: "chicken" %>Salé</div>
        <div class="nav22 icons"><%= image_tag "sweet.png", alt: "Sucré", id: "sweet" %>Sucré</div>
        <div class="nav33 icons"><%= image_tag "soda.png", alt: "Soft", id: "soda" %>Soft</div>
        <div class="nav44 icons"><%= image_tag "alcohol.png", alt: "Alcool", id: "alcohol" %>Alcool</div>
        <div class="small-square pos1"></div>
        <!-- <div class="blanc"></div> -->
      </div>

<!--       <div class="buttons-index">
        <div class="btn btn-primary btn-nav2 nav11">Salé</div>
        <div class="btn btn-primary btn-nav2 nav22">Sucré</div>
        <div class="btn btn-primary btn-nav2 nav33">Soft</div>
        <div class="btn btn-primary btn-nav2 nav44">Alcool</div>
      </div>
 -->
      <div class="slider-container">
        <div class="slider2 sale">

          <div class="slide-food">
            <div class="wishlist-card card-items category flex-wrap">
              <% @items.each do |item| %>
                <%= render 'select-item', category: "salé", event: @event, item: item, whishlists_per_item: @whishlists_per_item  %>
              <% end %>
            </div>
          </div>

          <div class="slide-food">
            <div class="wishlist-card card-items category d-flex flex-wrap">
              <% @items.each do |item| %>
                <%= render 'select-item', category: "sucré", event: @event, item: item, whishlists_per_item: @whishlists_per_item  %>
              <% end %>

            </div>
          </div>

          <div class="slide-food">
            <div class="wishlist-card card-items category d-flex flex-wrap">
              <% @items.each do |item| %>
                <%= render 'select-item', category: "soft", event: @event, item: item, whishlists_per_item: @whishlists_per_item  %>
              <% end %>

            </div>
          </div>

          <div class="slide-food">
            <div class="wishlist-card card-items category d-flex flex-wrap">
              <% @items.each do |item| %>
                <%= render 'select-item', category: "alcool", event: @event, item: item, whishlists_per_item: @whishlists_per_item  %>
              <% end %>
            </div>
          </div>

        </div>
      </div>

<!-- </div> -->

<% end %>
<!-- <div class="btn-flex w-100">
</div> -->
<div class="org-meal-wrapper">
  <%= link_to "Valider ton meal",  event_baskets_path(@event), :class => "btn btn-info mauve org-meal" %>
</div>

<%#= link_to whishlist.item.name, event_whishlist_path(whishlist.event_id, whishlist.id), method: :put %>  <%#= whishlist.quantity %>

app/views/whishlists/new.html.erb
<h1>Whishlists#new</h1>
<p>Find me in app/views/whishlists/new.html.erb</p>

app/views/whishlists/update.js.erb
// function updateQuantity() {
//   const itemQuantity = document.getElementById("whishlist-item-id-<%= @whishlist.id %>");
//   itemQuantity.innerHTML = "<%= j render 'button-basket', whishlist: @whishlist %>";
//   <% if @whishlist.quantity.zero? %>
//     itemQuantity.remove();
//   <% end %>
// }

// updateQuantity();